export const AUTH_GET_ME = 'auth/AUTH_GET_ME';
export const AUTH_LOGOUT = 'auth/AUTH_LOGOUT';

export const MAIN_GET_MAIN = 'main/MAIN_GET_MAIN';
export const MAIN_LIKE_REVIEW = 'main/MAIN_LIKE_REVIEW';
export const MAIN_UNLIKE_REVIEW = 'main/MAIN_UNLIKE_REVIEW';

export const STORE_GET_STORE = 'store/STORE_GET_STORE';
export const STORE_FAVORITE_STORE = 'store/STORE_FAVORITE_STORE';
export const STORE_UN_FAVORITE_STORE = 'store/STORE_UN_FAVORITE_STORE';

export const STORE_LIKE_REVIEW = 'store/STORE_LIKE_REVIEW';
export const STORE_UNLIKE_REVIEW = 'store/STORE_UNLIKE_REVIEW';
export const STORE_CREATE_COMMENT = 'store/STORE_CREATE_COMMENT';
export const STORE_DELETE_COMMENT = 'store/STORE_DELETE_COMMENT';

export const SEARCH_INIT_DATA = 'search/SEARCH_INIT_DATA';
export const SEARCH_INIT_MAP = 'search/SEARCH_INIT_MAP';

export const WIKI_GET_WIKI = 'wiki/WIKI_GET_WIKI';
export const WIKI_DELETE_WIKI = 'wiki/WIKI_DELETE_WIKI';
export const WIKI_FAVORITE_WIKI = 'wiki/WIKI_FAVORITE_WIKI';
export const WIKI_UN_FAVORITE_WIKI = 'wiki/WIKI_UN_FAVORITE_WIKI';

export const WIKI_DETAIL_GET_DETAIL = 'wikiDetail/WIKI_DETAIL_GET_DETAIL';
export const WIKI_DETAIL_FAVORITE_WIKI = 'wikiDetail/WIKI_DETAIL_FAVORITE_WIKI';
export const WIKI_DETAIL_UN_FAVORITE_WIKI = 'wikiDetail/WIKI_DETAIL_UN_FAVORITE_WIKI';
export const WIKI_DETAIL_CREATE_COMMENT = 'wikiDetail/WIKI_DETAIL_CREATE_COMMENT';
export const WIKI_DETAIL_DELETE_COMMENT = 'wikiDetail/WIKI_DETAIL_DELETE_COMMENT';
