export const AUTH_GET_ME = 'auth/AUTH_GET_ME';
export const AUTH_LOGOUT = 'auth/AUTH_LOGOUT';

export const MAIN_GET_MAIN = 'main/MAIN_GET_MAIN';
export const MAIN_LIKE_REVIEW = 'main/MAIN_LIKE_REVIEW';
export const MAIN_UNLIKE_REVIEW = 'main/MAIN_UNLIKE_REVIEW';
export const MAIN_STORE_FAVORITE = 'search/MAIN_STORE_FAVORITE';
export const MAIN_STORE_UNFAVORITE = 'search/MAIN_STORE_UNFAVORITE';
export const MAIN_WIKI_FAVORITE = 'search/MAIN_WIKI_FAVORITE';
export const MAIN_WIKI_UNFAVORITE = 'search/MAIN_WIKI_UNFAVORITE';
export const MAIN_REVIEW_LIKE = 'search/MAIN_REVIEW_LIKE';
export const MAIN_REVIEW_UNLIKE = 'search/MAIN_REVIEW_UNLIKE';

export const STORE_GET_STORE = 'store/STORE_GET_STORE';
export const STORE_FAVORITE_STORE = 'store/STORE_FAVORITE_STORE';
export const STORE_UN_FAVORITE_STORE = 'store/STORE_UN_FAVORITE_STORE';
export const STORE_REVIEW_LIKE = 'store/STORE_REVIEW_LIKE';
export const STORE_REVIEW_UNLIKE = 'store/STORE_REVIEW_UNLIKE';

export const SEARCH_INIT_DATA = 'search/SEARCH_INIT_DATA';
export const SEARCH_FAVORITE = 'search/SEARCH_FAVORITE';
export const SEARCH_UNFAVORITE = 'search/SEARCH_UNFAVORITE';

export const WIKI_GET_WIKI = 'wiki/WIKI_GET_WIKI';
export const WIKI_DELETE_WIKI = 'wiki/WIKI_DELETE_WIKI';
export const WIKI_FAVORITE_WIKI = 'wiki/WIKI_FAVORITE_WIKI';
export const WIKI_UN_FAVORITE_WIKI = 'wiki/WIKI_UN_FAVORITE_WIKI';

export const WIKI_DETAIL_GET_DETAIL = 'wikiDetail/WIKI_DETAIL_GET_DETAIL';
export const WIKI_DETAIL_FAVORITE_WIKI = 'wikiDetail/WIKI_DETAIL_FAVORITE_WIKI';
export const WIKI_DETAIL_UN_FAVORITE_WIKI = 'wikiDetail/WIKI_DETAIL_UN_FAVORITE_WIKI';
export const WIKI_DETAIL_CREATE_COMMENT = 'wikiDetail/WIKI_DETAIL_CREATE_COMMENT';
export const WIKI_DETAIL_DELETE_COMMENT = 'wikiDetail/WIKI_DETAIL_DELETE_COMMENT';
